
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --workers 3 --bind 0.0.0.0:80 tinrate_api.wsgi:application
    volumes:
      - .:/app
    ports:
      - "80:80"
    env_file:
      - .env
    restart: unless-stopped
