# Generated by Django 5.1.7 on 2025-03-18 08:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('users', '0004_company_experience_role_remove_user_is_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='duration',
        ),
        migrations.AddField(
            model_name='listing',
            name='availability',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.company'),
        ),
        migrations.AddField(
            model_name='listing',
            name='experience',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.experience'),
        ),
        migrations.AddField(
            model_name='listing',
            name='role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.role'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
