# Generated by Django 5.1.7 on 2025-03-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_price_listing_amount_remove_listing_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='company',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='role',
        ),
    ]
