# Generated by Django 5.1.7 on 2025-03-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_price_listing_amount_remove_listing_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listing',
            table='listings',
        ),
    ]
