# Generated by Django 5.1.7 on 2025-03-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_day_rename_amount_listing_pricing_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='listing',
        ),
        migrations.AlterField(
            model_name='listing',
            name='availability',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.availability'),
        ),
    ]
