# Generated by Django 5.2.1 on 2025-06-02 12:21

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(help_text="When the meeting is scheduled"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Meeting duration in minutes",
                        validators=[django.core.validators.MinValueValidator(15)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        help_text="Current status of the meeting",
                        max_length=20,
                    ),
                ),
                (
                    "meeting_url",
                    models.URLField(
                        blank=True, help_text="URL for the video meeting", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Meeting notes or agenda"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
                "db_table": "meetings",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(help_text="Requested meeting time"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Requested meeting duration in minutes",
                        validators=[django.core.validators.MinValueValidator(15)],
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Message from client to expert"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        help_text="Status of the invitation",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Meeting Invitation",
                "verbose_name_plural": "Meeting Invitations",
                "db_table": "meeting_invitations",
                "ordering": ["-created_at"],
            },
        ),
    ]
