# Generated by Django 5.1.7 on 2025-03-18 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_allow_cancellation_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_expert',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.JSONField(blank=True, null=True)),
                ('account_security', models.JSONField(blank=True, null=True)),
                ('notification_pref', models.JSONField(blank=True, null=True)),
                ('payment_settings', models.JSONField(blank=True, null=True)),
                ('support_help', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, null=True)),
                ('profile_picture', models.CharField(max_length=64, null=True)),
                ('total_meetings', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('career_title', models.CharField(max_length=64, null=True)),
                ('career_location', models.CharField(max_length=64, null=True)),
                ('career_status', models.CharField(choices=[('part-time', 'Part-time'), ('full-time', 'Full-time')], max_length=50, null=True)),
                ('career_description', models.CharField(max_length=64, null=True)),
                ('career_picture', models.CharField(max_length=64, null=True)),
                ('education_location', models.CharField(max_length=64, null=True)),
                ('education_diploma', models.CharField(max_length=64, null=True)),
                ('education_description', models.TextField(max_length=500, null=True)),
                ('education_picture', models.CharField(max_length=64, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='users.company')),
                ('experience_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_experiences', to='users.experience')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='users.role')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
