# Generated by Django 5.1.7 on 2025-03-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_company_experience_role_remove_user_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
