# Generated by Django 5.1.7 on 2025-03-20 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_company_remove_listing_experience_and_more'),
        ('users', '0005_remove_user_allow_cancellation_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='career_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='career_location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='career_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='career_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='career_title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_diploma',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_id',
        ),
        migrations.AddField(
            model_name='experience',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Unknown', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(default='Unknown', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meetings_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='weight',
            field=models.IntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=64)),
                ('job_status', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time')], max_length=64)),
                ('description', models.TextField(max_length=500)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='career_pictures/')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=64)),
                ('diploma', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=500)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='education_pictures/')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comment', models.TextField(max_length=500)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
