# Generated by Django 5.1.7 on 2025-03-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='user_role',
        ),
    ]
