# Generated by Django 5.1.7 on 2025-03-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_role_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='user_company',
        ),
    ]
