# Generated by Django 5.1.7 on 2025-03-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_supportticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='profile',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
