# Generated by Django 5.1.7 on 2025-03-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_settings_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='account_security',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='notification_pref',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='payment_settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='support_help',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
