# Generated by Django 5.2.1 on 2025-06-02 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experts", "0002_initial"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewsummary",
            name="expert",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_summary",
                to="experts.expert",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("meeting",), name="unique_review_per_meeting"
            ),
        ),
    ]
