# Generated by Django 5.2.1 on 2025-06-02 12:21

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Specific date (for date-specific availability)",
                        null=True,
                    ),
                ),
                (
                    "weekday",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        help_text="Weekday (for weekly default availability)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Start time of availability slot"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="End time of availability slot"),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Whether this time slot is available"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this time slot is enabled (for weekly defaults)",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone for this availability slot",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Expert Availability",
                "verbose_name_plural": "Expert Availability",
                "db_table": "expert_availability",
                "ordering": ["date", "weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Expert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Expert's professional title", max_length=200
                    ),
                ),
                (
                    "company",
                    models.CharField(help_text="Expert's company name", max_length=200),
                ),
                (
                    "bio",
                    models.TextField(help_text="Expert's biography", max_length=500),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expert's hourly rate in USD",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(1.0)],
                    ),
                ),
                (
                    "skills",
                    models.JSONField(default=list, help_text="List of expert's skills"),
                ),
                (
                    "profile_url",
                    models.SlugField(
                        help_text="Custom URL for expert's profile", unique=True
                    ),
                ),
                (
                    "is_listed",
                    models.BooleanField(
                        default=False, help_text="Whether the expert is publicly listed"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Whether the expert is featured"
                    ),
                ),
                (
                    "is_top_rated",
                    models.BooleanField(
                        default=False, help_text="Whether the expert is top-rated"
                    ),
                ),
                (
                    "company_logo",
                    models.URLField(
                        blank=True, help_text="URL to company logo", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Expert",
                "verbose_name_plural": "Experts",
                "db_table": "experts",
                "ordering": ["-created_at"],
            },
        ),
    ]
