# Generated by Django 5.2.1 on 2025-06-02 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expert_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_slots",
                to="experts.expert",
            ),
        ),
        migrations.AddConstraint(
            model_name="availability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("date__isnull", False), ("weekday__isnull", True)),
                    models.Q(("date__isnull", True), ("weekday__isnull", False)),
                    _connector="OR",
                ),
                name="availability_date_or_weekday",
            ),
        ),
    ]
