# Generated by Django 5.2.1 on 2025-06-02 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive email notifications"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive push notifications"
                    ),
                ),
                (
                    "meeting_reminders",
                    models.BooleanField(
                        default=True, help_text="Receive meeting reminder notifications"
                    ),
                ),
                (
                    "review_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive review notifications"
                    ),
                ),
                (
                    "payment_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive payment notifications"
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        default=False, help_text="Receive marketing emails"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("meeting_reminder", "Meeting Reminder"),
                            ("meeting_scheduled", "Meeting Scheduled"),
                            ("meeting_cancelled", "Meeting Cancelled"),
                            ("meeting_completed", "Meeting Completed"),
                            ("review_received", "Review Received"),
                            ("profile_approved", "Profile Approved"),
                            ("profile_rejected", "Profile Rejected"),
                            ("payment_received", "Payment Received"),
                            ("system_announcement", "System Announcement"),
                            ("expert_application", "Expert Application"),
                            ("general", "General"),
                        ],
                        help_text="Type of notification",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                ("message", models.TextField(help_text="Notification message")),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to navigate to when notification is clicked",
                        null=True,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification has been read",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
